info:
    app:
        version: '@version@'
    author: Artur Medrala
    java:
        version: '@java.version@'
    mail: axxrxxo@gmail.com
management:
    endpoint:
        health:
            show-details: always
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: '*'



metrics:
    export:
        prometheus:
            enables: true
server:

    tomcat:
        connection-timeout: 120
spring:
    cache:
        caffeine:
            spec: expireAfterWrite=300s
    datasource:
        password: Henry6591@
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    flyway:
        baseline-on-migrate: false
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show-sql: true
    profiles:
        active: ''
